### ISSUE TITLE
NOTIFICATION & REMINDER

### ISSUE THREAD

**Issue by vasnt** [grams/task-focused-browser-tabs#2]
- Is there anyway to setup notification/reminders assigned with calendar/date for tasks?
- Or any other similar/alternative web extension exist for task management with reminder/notification

**Comment by grams** [comment]
First question: nope, sorry.
However, for the second question I have recently rebuilt the extension to work with Trello. The home-made kanban UI is very poor and very quick&dirty. I moved to another implementation that works with Trello board and collaborates with a trello power-up. This means that for tasks and reminders you are just using regular trello. The list of open tabs is not stored in your google account but as private data on each trello card.
It is not publicly released yet but I can ping you when it is.

**Comment by vasnt** [comment]
thanks grams, please ping me when it is ready, excited to try it.
